### ISSUE TITLE
how to install malscan-db?

### ISSUE THREAD

**Issue by vay3t** [malscan/malscan#27]
how to install malscan-db?

```
[root@hardening ~]# rpm -i https://github.com/malscan/malscan/releases/download/v1.8.1/malscan-1.8.1-1.el7.noarch.rpm
advertencia:/var/tmp/rpm-tmp.8wyivG: EncabezadoV4 RSA/SHA1 Signature, ID de clave 05040f25: NOKEY
error: Error de dependencias:
	malscan-db es necesario por malscan-1.8.1-1.el7.noarch
```

**Comment by jgrancell** [comment]
You either need to install the malscan repository, so that you can run `yum install malscan` and let it handle dependencies, or you need to manually install the `malscan-db` package.

You can enable the malscan repository by following the correct install guide for your OS:
* [CentOS 7 and similar](https://malscan.readthedocs.io/en/latest/guides/installation/centos7/)
* [CentOS 6 and similar](https://malscan.readthedocs.io/en/latest/guides/installation/centos6/)

If you want to manually download and install the `malscan-db` RPM you can do so with either of these links:
* [CentOS 7 and similar](http://yum.malscan.org/el/7/malscan-db-1.0.2-1.noarch.rpm)
* [CentOS 6 and similar](http://yum.malscan.org/el/6/malscan-db-1.0.2-1.noarch.rpm)

If you manually installed and you're trying to upgrade, you should just be able to run `malscan -u` and the self-updater will take care of it.

**Comment by vay3t** [comment]
this link not open http://yum.malscan.org/el/7/malscan-db-1.0.2-1.noarch.rpm

**Comment by jgrancell** [comment]
It should work now.
